version: "3.8"
    
services:
    chronograf:
        container_name: chronograf
        image: chronograf:1.8.4-alpine
        volumes:
            - docker_data:/var/lib/chronograf
        environment:
            - BOLT_PATH=/var/lib/chronograf/chronograf-v1.db
        networks:
            - fabric
        ports:
            - "8200:8888"
            - "8201:10000"
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    cpus: '0.2'
                    memory: 80m
                reservations:
                    cpus: '0.1'
                    memory: 40m
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 60s
            
    influxdb:
        container_name: influxdb
        image: influxdb:1.8.1-alpine
        volumes:
            - docker_data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=container_metrics
            - INFLUXDB_ADMIN_USER=DerAdmin
            - INFLUXDB_ADMIN_PASSWORD=667wasd
            - INFLUXDB_WRITE_USER=telegraf
            - INFLUXDB_WRITE_USER_PASSWORD=telepass
            - INFLUXDB_READ_USER=chrono
            - INFLUXDB_READ_USER_PASSWORD=KronosGaiaUranus
        networks:
            - fabric
        ports:
            - "8100:8086"
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    cpus: '0.3'
                    memory: 300m
                reservations:
                    cpus: '0.2'
                    memory: 150m
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 60s
        
    telegraf:
        container_name: telegraf
        hostname: SoSe2020
        image: telegraf:1.15-alpine
        environment:
            - HOST_PROC=/host/proc
            - HOST_SYS=/host/sys
            - HOST_ETC=/host/etc
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys:/host/sys:ro
            - /proc:/host/proc:ro
            - /etc:/host/etc:ro
        networks:
            - fabric
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 150m
                reservations:
                    cpus: '0.1'
                    memory: 80m
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 60s

    kapacitor:
        container_name: kapacitor
        image: kapacitor:1.5.5-alpine
        volumes:
            - "./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro"
            - "docker_data:/var/lib/kapacitor"
        networks:
            - fabric
        ports:
            - "8300:9092"
        deploy:
            placement:
                constraints: 
                    - "node.role==manager"
            resources:
                limits:
                    cpus: '0.1'
                    memory: 100m
                reservations:
                    cpus: '0.05'
                    memory: 30m
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 60s


volumes:
    docker_data:
            
networks:
    fabric:
        driver: overlay
        driver_opts:
            encrypted: "true"