version: "3.8"
    
services:
    chronograf:
        container_name: chronograf
        image: chronograf:1.8.4-alpine
        restart: always
        volumes:
            - metricen:/var/lib/chronograf
        environment:
            - BOLT_PATH=/var/lib/chronograf/chronograf-v1.db
        networks:
            - datenautobahn
        ports:
            - "8200:8888"
            - "8201:10000"
            
    influxdb:
        container_name: influxdb
        image: influxdb:1.8.1-alpine
        volumes:
            - metricen:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=container_metrics
            - INFLUXDB_ADMIN_USER=DerAdmin
            - INFLUXDB_ADMIN_PASSWORD=667wasd
            - INFLUXDB_WRITE_USER=telegraf
            - INFLUXDB_WRITE_USER_PASSWORD=telepass
            - INFLUXDB_READ_USER=chrono
            - INFLUXDB_READ_USER_PASSWORD=KronosGaiaUranus
        networks:
            - datenautobahn
        ports:
            - "8100:8086"
        
    telegraf:
        container_name: telegraf
        hostname: SoSe2020
        image: telegraf:1.15-alpine
        restart: always
        environment:
            - HOST_PROC=/host/proc
            - HOST_SYS=/host/sys
            - HOST_ETC=/host/etc
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys:/host/sys:ro
            - /proc:/host/proc:ro
            - /etc:/host/etc:ro
        networks:
            - datenautobahn

    kapacitor:
        container_name: kapacitor
        image: kapacitor:1.5.5-alpine
        restart: always
        volumes:
            - "./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro"
            - "metricen:/var/lib/kapacitor"
        networks:
            - datenautobahn
        ports:
            - "8300:9092"


volumes:
    metricen:
            
networks:
    datenautobahn:
        driver: bridge